// Code generated by golib; DO NOT EDIT.
package main

import (
	"helloworld/configx"
	"helloworld/cronjobx"
	_ "helloworld/model"
	"helloworld/router"
	_ "helloworld/service"

	"github.com/forbearing/golib/bootstrap"
	. "github.com/forbearing/golib/util"
)

func main() {
	RunOrDie(bootstrap.Bootstrap)
	RunOrDie(configx.Init)
	RunOrDie(cronjobx.Init)
	RunOrDie(router.Init)
	RunOrDie(bootstrap.Run)
}
